ecommerce/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls')),
    path('users/', include('userapp.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from. import views

app_name = 'store'

urlpatterns = [
    path('', views.store, name='store'),
    path('cart/', views.cart, name='cart'),
    path('checkout/', views.checkout, name='checkout'),
    path('update_item/', views.updateItem, name='update_item')
]

userapp/urls.py
from django.urls import path
from django.contrib.auth import views as auth_view
from . import views

app_name = 'userapp'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', auth_view.LoginView.as_view(template_name ='userapp/login.html'), name='login'),
    path('logout/', auth_view.LogoutView.as_view(template_name='userapp/logout.html'), name='logout')
]

store/models.py
from django.db import models
from django.db.models.expressions import F
from userapp.models import User

class Customer(models.Model):
    user = models.OneToOneField(User, null=True, blank=True, on_delete=models.CASCADE)
    name = models.CharField(max_length=200, null=True, blank=True)
    
    def __str__(self):
        return self.user.first_name + ' ' + self.user.last_name

class Product(models.Model):
    name = models.CharField(max_length=200)
    price = models.FloatField()
    active = models.BooleanField(default=True,null=True, blank=True)
    quantity = models.PositiveBigIntegerField(default=1)
    image = models.ImageField(null=True, blank=True)

    class Meta:
        ordering = ['id']

    def __str__(self):
        return self.name

    @property
    def imageURL(self):
        try:
            url = self.image.url
        except:
            url = ''
        return url

    
class Order(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE, blank=True, null=True)
    date_order = models.DateTimeField(auto_now_add=True)
    complete = models.BooleanField(default=False, null=True, blank=True)
    transaction_id = models.CharField(max_length=200, null=True)

    def __str__(self):
        return self.customer.name
    
    @property
    def get_cart_total(self):
        orderitems = self.orderitem_set.all() 
        total = sum([item.get_total for item in orderitems])
        return total

    @property
    def get_cart_items(self):
        orderitems = self.orderitem_set.all() 
        total = sum([item.quantity for item in orderitems])
        return total

class OrderItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True, blank=True)
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, blank=True, null=True)
    quantity = models.IntegerField(default=0, null=True, blank=True)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.product.name

    @property
    def get_total(self):
        total = self.product.price * self.quantity
        return total

class ShippingAddress(models.Model):
    customer = models.ForeignKey(User, on_delete=models.SET_NULL, blank=True, null=True)
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, blank=True, null=True)
    address = models.CharField(max_length=255,null=False, blank=False)
    city = models.CharField(max_length=255,null=False, blank=False)
    state = models.CharField(max_length=255,null=False, blank=False)
    zipcode = models.CharField(max_length=255,null=False, blank=False)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.address

store/views.py
from django.shortcuts import render
from .models import *
from django.http import JsonResponse
import json
from django.contrib.auth.decorators import login_required


def store(request):
    if request.user.is_authenticated:
        customer = request.user.customer
        order, created = Order.objects.get_or_create(customer=customer, complete=False)
        items = order.orderitem_set.all()
        cartItems = order.get_cart_items
    else:
        items = []
        order = {'get_cart_items': 0, 'get_cart_total': 0}
        cartItems = order['get_cart_items']
    products = Product.objects.filter(active=True)
    context = {'products': products, 'cartItems': cartItems, 'shipping': False }
    return render(request, 'store/store.html', context)

@login_required
def cart(request):
    if request.user.is_authenticated:
        customer = request.user.customer
        order, created = Order.objects.get_or_create(customer=customer, complete=False)
        items = order.orderitem_set.all()
        cartItems = order.get_cart_items
    else:
        items = []
        order = {'get_cart_items': 0, 'get_cart_total': 0}
        cartItems = order['get_cart_items']
    context = {'items' : items, 'order': order, 'cartItems': cartItems,'shipping': False}
    return render(request, 'store/cart.html', context)

@login_required
def checkout(request):
    if request.user.is_authenticated:
        customer = request.user.customer
        order, created = Order.objects.get_or_create(customer=customer, complete=False)
        items = order.orderitem_set.all()
        cartItems = order.get_cart_items
    else:
        items = []
        order = {'get_cart_items': 0, 'get_cart_total': 0}
        cartItems = order['get_cart_items']
    context = {'items' : items, 'order': order, 'cartItems': cartItems, 'shipping': False}
    return render(request, 'store/checkout.html', context)

@login_required
def updateItem(request):
	data = json.loads(request.body)
	productId = data['productId']
	action = data['action']
	print('Action:', action)
	print('Product:', productId)

	customer = request.user.customer
	product = Product.objects.get(id=productId)
	order, created = Order.objects.get_or_create(customer=customer, complete=False)

	orderItem, created = OrderItem.objects.get_or_create(order=order, product=product)

	if action == 'add':
		orderItem.quantity = (orderItem.quantity + 1)
	elif action == 'remove':
		orderItem.quantity = (orderItem.quantity - 1)

	orderItem.save()

	if orderItem.quantity <= 0:
		orderItem.delete()

	return JsonResponse('Item was added', safe=False)

store/templates/store/cart.html
{% extends 'store/main.html' %}
{% load static %}
{% block content %}
<div class="row">
    <div class="col-lg-12">
        <div class="box-element">
            <a class="btn btn-outline-dark" href="{% url 'store:store' %}">&#x2190; Continue Shopping</a>
            <br>
            <br>
            <table class="table">
                <tr>
                    <th><h5>Items :<strong>{{ order.get_cart_items }}</strong></h5></th>
                    <th><h5>Total :<strong>&#8377; {{ order.get_cart_total|floatformat:2 }}</strong></h5></th>
                </tr>
                <th>
                    <a style="float: right; margin: 5px;" class="btn btn-success" href="{% url 'store:checkout' %}">Checkout</a>
                </th>
            </table>
        </div>
        <br>
        <div class="box-element">
            <div class="cart-row">
                <div style="flex: 2;"></div>
                <div style="flex: 2;"><strong>Item</strong></div>
                <div style="flex: 2;"><strong>Price</strong></div>
                <div style="flex: 1;"><strong>Quantity</strong></div>
                <div style="flex: 1;"><strong>Total</strong></div>
            </div>
            {% for item in items %}
				<div class="cart-row">
					<div style="flex:2"><img class="row-image" src="{{item.product.imageURL}}"></div>
					<div style="flex:2"><p>{{item.product.name}}</p></div>
					<div style="flex:1"><p>&#8377; {{item.product.price|floatformat:2}}</p></div>
					<div style="flex:1">
						<p class="quantity">{{item.quantity}}</p>
						<div class="quantity">
							<img data-product="{{item.product.id}}" data-action="add" class="chg-quantity update-cart" src="{% static  'images/arrow-up.png' %}">
					
							<img data-product="{{item.product.id}}" data-action="remove" class="chg-quantity update-cart" src="{% static  'images/arrow-down.png' %}">
						</div>
					</div>
					<div style="flex:1"><p>&#8377; {{item.get_total|floatformat:2}}</p></div>
				</div>
				{% endfor %}
        </div>
    </div>
</div>
{% endblock content %}

store/templates/store/checkout.html
{% extends 'store/main.html' %}
{% load static %}
{% block content %}
    <div class="row">
        <div class="col-lg-6" id="form-warpper">
            <div class="box-element">
                <form id="form">
                    <div id="user-info">
                        <div class="form-field">
							<input required class="form-control" type="text" name="name" placeholder="Name..">
						</div>
						<div class="form-field">
							<input required class="form-control" type="email" name="email" placeholder="Email..">
						</div>
                    </div>
                    <div id="shipping-info">
                        <hr>
						<p>Shipping Information:</p>
						<hr>
						<div class="form-field">
							<input class="form-control" type="text" name="address" placeholder="Address..">
						</div>
						<div class="form-field">
							<input class="form-control" type="text" name="city" placeholder="City..">
						</div>
						<div class="form-field">
							<input class="form-control" type="text" name="state" placeholder="State..">
						</div>
						<div class="form-field">
							<input class="form-control" type="text" name="zipcode" placeholder="Zip code..">
						</div>
						<div class="form-field">
							<input class="form-control" type="text" name="country" placeholder="Zip code..">
						</div>
                    </div>
                    <hr>
					<input id="form-button" class="btn btn-success btn-block" type="submit" value="Continue">
                </form>
            </div>
            <br>
            <div class="box-element hidden" id="payment-info">
                <img src="{% static 'images/Paytm.png' %}" width="90", height="90">
                <button id="make-payment">Make Payment</button>
            </div>
        </div>
        <div class="col-lg-6">
            <div class="box-element">
                <a class="btn btn-outline-dark" href="{% url 'store:cart' %}">&#x2190; Back to cart</a>
                <hr>
                <h3>Order Summary</h3>
                <hr>
                {% for item in items %}
                <div class="cart-row">
                    <div style="flex:2"><img class="row-image" src="{{ item.product.imageURL }}"></div>
                    <div style="flex:2"><p>{{ item.product.name }}</p></div>
                    <div style="flex:1"><p>&#8377; {{ item.product.price|floatformat:2 }}</p></div>
                    <div style="flex:1"><p>X {{ item.quantity }}</p></div>
                </div> 
                {% endfor %}
                <h5>Items: {{ order.get_cart_items }}</h5>
                <h5>Total: &#8377; {{ order.get_cart_total|floatformat:2 }}</h5>
            </div> 
        </div>
    </div>
    <script type="text/javascript">
        var shipping = '{{ order.shipping }}'
        var total = '{{ order.get_cart_total|floatformat:2 }}'
        if(shipping == 'False'){
            document.getElementById("shipping-info").innerHTML = ''
        }

        if (user != 'AnonymousUser'){
		 	document.getElementById('user-info').innerHTML = ''
		 }

		if (shipping == 'False' && user != 'AnonymousUser'){
				document.getElementById('form-wrapper').classList.add("hidden");
			    document.getElementById('payment-info').classList.remove("hidden");
		}

        var form = document.getElementById('form')
        form.addEventListener('submit', function(e){
            e.preventDefault()
            console.log('Form Submitted...')
            document.getElementById('form-button').classList.add('hidden')
            document.getElementById('payment-info').classList.remove('hidden')
        })

        document.getElementById("make-payment").addEventListener('click', function(e){
            submitFormData()
        })

        function submitFormData(){
            console.log('Button cloicked....')
        }
    </script>
{% endblock content %}

store/templates/store/main.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1, minimum-scale=1">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <title>Ecom</title>
    <script>
        var user = '{{ request.user }}'
        function getToken(name) {
          var cookieValue = null;
          if (document.cookie && document.cookie !== '') {
              var cookies = document.cookie.split(';');
              for (var i = 0; i < cookies.length; i++) {
                  var cookie = cookies[i].trim();
                  // Does this cookie string begin with the name we want?
                  if (cookie.substring(0, name.length + 1) === (name + '=')) {
                      cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                      break;
                  }
              }
          }
          return cookieValue;
      }
      var csrftoken = getToken('csrftoken')
    </script>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="{% url 'store:store' %}">Invevtory</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'store:store' %}">Store <span class="sr-only">(current)</span></a>
            </li>
            {% if not user.is_authenticated %}
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'userapp:login' %}">Login <span class="sr-only">(current)</span></a>
              </li>
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'userapp:register' %}">Register <span class="sr-only">(current)</span></a>
              </li>
            {% endif %}
          </ul>
          {% if user.is_authenticated %}
            <div class="form-inline my-2 my-lg-0">
              <a href="{% url 'userapp:logout' %}" class="btn btn-warning">Logout</a>
              <a href="{% url 'store:cart' %}">
                  <img id="cart-icon" src="{% static 'images/cart.png'%}">
              </a>
              <p id="cart-total">{{ cartItems }}</p>
            </div>
          {% endif %}
        </div>
      </nav>
    <hr>
    <div class="container">
        {% block content %}
        {% endblock content%}
    </div>
    

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script type="text/javascript" src="{% static 'js/cart.js' %}"></script>
</body>
</html>

store/templates/store/store.html
{% extends 'store/main.html' %}
{% load static %}
{% block content %}
    <div class=row>
        {% for product in products %} 
        <div class="col-lg-4">
            <img class="thumbnail" src="{{ product.imageURL }}">
            <div class="box-element product">
                <h6><strong>{{ product.name }}</strong></h6>
                <hr>
                <button data-product="{{product.id}}" data-action="add" class="btn btn-outline-secondary add-btn update-cart">Add to Cart</button>
                <a class="btn btn-outline-success" href="{{product.imageURL}}">View</a>
                <h4 style="display: inline-block; float: right;">&#8377; {{ product.price|floatformat:2 }}</h4>
            </div>
        </div>
        {% endfor %}
    </div>
{% endblock content %}